import React, { Component } from 'react'
import {
  View,
  Text,
  FlatList,
  Image,
  StyleSheet,
  TouchableOpacity,
  Dimensions,
  ScrollView,
  WebView
} from 'react-native';

import Api from '../config/api'
import Styles from '../config/style';
import Colors from '../config/color';
import ArticleCard from '../components/articleCard';

const width = Dimensions.get('window').width;

const htmlContent = `
<div class="main-container">
<div class="article-content-inner" id="article-content-inner">
    <p style="margin: 0px 0px 6px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><img alt="shutterstock_131444474.jpg" src="https://pic.pimg.tw/joytraveldiving0/1552459198-919431575_n.jpg" title="shutterstock_131444474.jpg"></p>
    <p style="margin: 0px 0px 6px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">夏天即將到來，相信很多還没潛水證照的人已經摩拳擦掌準備學潛水啦~</span></span></p>
    <p style="margin: 0px 0px 6px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">但</span></span><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">在學潛水前，大家應該有很多疑問吧~今天小編就整理常被問的5個問</span></span></p>
    <p style="margin: 0px 0px 6px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">題</span></span><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">幫</span></span><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">大家解答!!</span></span></p>
    <p style="margin: 0px 0px 6px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</p>
    <p style="margin: 0px 0px 6px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="color:#510701"><span style="font-size:20px"><strong><span style="-webkit-text-stroke-width:0px; background-color:rgb(255, 255, 255); display:inline !important; float:none; font-family:微軟正黑體; font-style:normal; font-variant-caps:normal; font-variant-ligatures:normal; font-weight:400; letter-spacing:normal; orphans:2; text-align:start; text-decoration-color:initial; text-decoration-style:initial; text-indent:0px; text-transform:none; white-space:normal; widows:2; word-spacing:0px">✤&nbsp;</span></strong><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><strong>Q1~每個人都可以學潛水嗎？</strong></span></span></span></p>
    <p style="margin: 0px 0px 6px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><img alt="40586098_933775033477774_3711684469183217664_n.jpg" height="446" src="https://pic.pimg.tw/joytraveldiving0/1552459198-2610581170_n.jpg" title="40586098_933775033477774_3711684469183217664_n.jpg" width="596"><span style="font-size:18px"> </span><br>
    <span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span class="text_exposed_show" style="display:inline">潛水是一個很需要有著"<strong><span style="color:#123D76">健康身體</span></strong>"的運動，尤其是在潛水過程中，會有</span></span></span><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span class="text_exposed_show" style="display:inline">"水</span></span></span></p>
    <p style="margin: 0px 0px 6px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span class="text_exposed_show" style="display:inline">壓</span></span></span><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span class="text_exposed_show" style="display:inline">"等問題，並不是每個人都可以學喔~像是<span style="color:#8B1910"><strong>有心臟病、氣喘、癲癇等疾病</strong></span></span></span></span></p>
    <p style="margin: 0px 0px 6px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span class="text_exposed_show" style="display:inline"><span style="color:#8B1910"><strong>都不適合學習潛水，孕婦也不適合</strong></span>。</span></span></span></p>
    <p style="margin: 0px 0px 6px; display: block; font-family: Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><br>
    <span style="color:rgb(29, 33, 41); font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span class="text_exposed_show" style="display:inline"><span style="color:#123D76"><strong>小編建議學潛水前，可以先詢問過醫生自己適不適合潛水，會比較適</strong></span></span></span></span><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span class="text_exposed_show" style="display:inline"><strong><font color="#123d76">當喔!</font></strong></span></span></span></p>
    <p style="margin: 0px 0px 6px; display: block; font-family: Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</p>
    <p style="margin: 0px 0px 6px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:20px"><strong><span style="color:#510701"><span style="-webkit-text-stroke-width:0px; background-color:rgb(255, 255, 255); display:inline !important; float:none; font-family:微軟正黑體; font-style:normal; font-variant-caps:normal; font-variant-ligatures:normal; font-weight:400; letter-spacing:normal; orphans:2; text-align:start; text-decoration-color:initial; text-decoration-style:initial; text-indent:0px; text-transform:none; white-space:normal; widows:2; word-spacing:0px">✤&nbsp;</span><span style="font-family:lucida sans unicode,lucida grande,sans-serif">Q2~選哪一個潛水系統好？</span></span></strong></span></p>
    <p style="margin: 6px 0px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><img alt="40538912_933776563477621_8346633203011813376_n.jpg" src="https://pic.pimg.tw/joytraveldiving0/1552459198-1885568806_n.jpg" title="40538912_933776563477621_8346633203011813376_n.jpg"><br>
    <span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">國際上認可的潛水系統非常多，像是PADI、SSI、CMAS、SDI、ADS、</span></span></p>
    <p style="margin: 6px 0px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">NAUI等這麼多系統，相信像小編一樣有"選擇困難症"的人一定都會很困</span></span><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">擾</span></span><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">。</span></span></p>
    <p style="margin: 6px 0px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">其實不管哪個系統學的都差不多，而且只要是<span style="color:#123D76"><strong>國際上有認可</strong></span>，基本上到國</span></span></p>
    <p style="margin: 6px 0px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">外</span></span><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">都是可被潛店接受。</span></span></p>
    <p style="margin: 6px 0px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><br>
    <span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span style="color:#123D76"><strong>小編認為比起系統更需要被重視的是"教練"，一個盡責用心的教練，才能</strong></span></span></span></p>
    <p style="margin: 6px 0px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span style="color:#123D76"><strong>教</strong></span></span></span><span style="color:#123D76"><strong><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">予你正確的潛水觀練與姿勢，才能讓您每一次潛水都平平安安!</span></span></strong></span></p>
    <p style="margin: 6px 0px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</p>
    <p style="margin: 6px 0px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="color:#510701"><span style="font-size:20px"><strong><span style="-webkit-text-stroke-width:0px; background-color:rgb(255, 255, 255); display:inline !important; float:none; font-family:微軟正黑體; font-style:normal; font-variant-caps:normal; font-variant-ligatures:normal; font-weight:400; letter-spacing:normal; orphans:2; text-align:start; text-decoration-color:initial; text-decoration-style:initial; text-indent:0px; text-transform:none; white-space:normal; widows:2; word-spacing:0px">✤&nbsp;</span><span style="font-family:lucida sans unicode,lucida grande,sans-serif">Q3~學潛水需要幾天的時間？</span></strong></span></span></p>
    <p style="margin: 6px 0px; display: block; font-family: Helvetica, Arial, sans-serif; color: rgb(29, 33, 41); font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><img alt="44136670_955341314654479_7734116835913629696_n.jpg" src="https://pic.pimg.tw/joytraveldiving0/1552459198-3651814503_n.jpg" title="44136670_955341314654479_7734116835913629696_n.jpg"></p>
    <div class="text_exposed_show" style="display: inline; color: rgb(29, 33, 41); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">這個問題，小編認為就是<span style="color:#123D76"><strong>看個人</strong></span>，以OW課程為例，課程通常是學科一堂，</span></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">平靜水域兩堂，開放水域四支氣瓶(要分兩天)，如果您是想輕輕鬆鬆、悠哉</span></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">悠哉的學，可以上到5天，如果您想盡快學會，3天也是可以。</span></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;">&nbsp;</p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><strong><span style="color:#123D76">就依照您自</span></strong></span></span><strong><span style="color:#123D76"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">己的時間來安排天數就可以了~</span></span></span></strong></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;">&nbsp;</p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="color:#510701"><span style="font-size:20px"><strong><span style="-webkit-text-stroke-width:0px; background-color:rgb(255, 255, 255); display:inline !important; float:none; font-family:微軟正黑體; font-style:normal; font-variant-caps:normal; font-variant-ligatures:normal; font-weight:400; letter-spacing:normal; orphans:2; text-align:start; text-decoration-color:initial; text-decoration-style:initial; text-indent:0px; text-transform:none; white-space:normal; widows:2; word-spacing:0px">✤&nbsp;</span><span style="font-family:lucida sans unicode,lucida grande,sans-serif">Q4~怎麼挑選潛店？</span></strong></span></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><img alt="S__6111285.jpg" src="https://pic.pimg.tw/joytraveldiving0/1552459198-892447830_n.jpg" title="S__6111285.jpg"><br>
    <span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">服務、價格、硬體、合法度、專業度等，都是挑選潛店非常重要的考慮項</span></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">目之一。網際網路的時代，上網查潛店評價，一定是大家最常做的事情，</span></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">潛水是一個<strong><span style="color:#123D76">專業性高</span></strong>的運動，千萬不要貪小便宜，免得吃虧的是自己。</span></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><br>
    <span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span style="color:#123D76"><strong>如果真的不知道如何選擇潛店，那就來找【&nbsp;潛盟&nbsp;】吧~我們嚴選專業又合</strong></span></span></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="color:#123D76"><strong><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">法教練，就是希望大家可以將潛水學好，開開心心FUN潛水~</span></span></strong></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;">&nbsp;</p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><strong><span style="color:#510701"><span style="font-size:20px"><span style="-webkit-text-stroke-width:0px; background-color:rgb(255, 255, 255); display:inline !important; float:none; font-family:微軟正黑體; font-style:normal; font-variant-caps:normal; font-variant-ligatures:normal; font-weight:400; letter-spacing:normal; orphans:2; text-align:start; text-decoration-color:initial; text-decoration-style:initial; text-indent:0px; text-transform:none; white-space:normal; widows:2; word-spacing:0px">✤&nbsp;</span><span style="font-family:lucida sans unicode,lucida grande,sans-serif">Q5~應該要買裝備嗎？</span></span></span></strong></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><img alt="潛裝備頁面-01_04_04.jpg" height="430" src="https://pic.pimg.tw/joytraveldiving0/1541067457-3490871667_n.jpg" title="潛裝備頁面-01_04_04.jpg" width="631"></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span style="color:#123D76"><strong>學潛水基本上是不用買裝備的喔~</strong></span>潛店都會提供學員在學期期間所需要的輕</span></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">重裝備，學完以後，您可以評估自己是否需要購買，因為一般潛店都是可以</span></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">租借裝備，非常方便!</span></span><br>
    &nbsp;</p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="color:#123D76"><strong><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">小編建議學完潛水後，可以先購買輕裝，因為比較貼身會有衛生問題。</span></span></strong></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;">&nbsp;</p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif">潛水是件"<span style="color:#123D76"><strong>非常舒壓又寧靜</strong></span>"的運動，如果你對潛水已經有興趣，那就快來"<span style="color:#123D76"><strong>學</strong></span></span></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;"><span style="font-size:18px"><span style="font-family:lucida sans unicode,lucida grande,sans-serif"><span style="color:#123D76"><strong>潛水</strong></span>"享受這項運動吧<span class="_5mfr" style="margin:0px 1px"><span class="_6qdm" style="background-image:url(&quot;https://static.xx.fbcdn.net/images/emoji.php/v9/t7f/1/16/1f60a.png&quot;); background-repeat:no-repeat; background-size:contain; color:transparent; display:inline-block; height:16px; text-decoration:none; text-shadow:none; vertical-align:text-bottom; width:16px">&#128522;</span></span>~</span></span></p>
    <p style="font-family: inherit; font-size: 15px; margin: 6px 0px;">&nbsp;</p>
    <p style="margin: 6px 0px;"><span style="font-size:20px"><span style="color:#8B1910"><span style="-webkit-text-stroke-width:0px; background-color:rgb(255, 255, 255); display:inline !important; float:none; font-family:微軟正黑體; font-style:normal; font-variant-caps:normal; font-variant-ligatures:normal; font-weight:400; letter-spacing:normal; orphans:2; text-align:start; text-decoration-color:initial; text-decoration-style:initial; text-indent:0px; text-transform:none; white-space:normal; widows:2; word-spacing:0px">✦</span> </span><a href="https://www.joytravel.com.tw/product.php?lang=tw&amp;tb=1&amp;cid=167" target="_blank"><span style="color:#8B1910"><font face="lucida sans unicode, lucida grande, sans-serif">潛盟潛水考照課程請點我</font></span></a><span style="color:#8B1910"> <span style="-webkit-text-stroke-width:0px; background-color:rgb(255, 255, 255); display:inline !important; float:none; font-family:微軟正黑體; font-style:normal; font-variant-caps:normal; font-variant-ligatures:normal; font-weight:400; letter-spacing:normal; orphans:2; text-align:start; text-decoration-color:initial; text-decoration-style:initial; text-indent:0px; text-transform:none; white-space:normal; widows:2; word-spacing:0px">✦</span></span></span></p>
</div>
</div>`
  ;

const styles = StyleSheet.create({
  content: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.lightGray
  }
})

export default class ArticleTest extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      htmlTxt: ``
    }
  }

  // componentDidMount = async () => {
  //   const { navigate } = this.props.navigation;
  //   try {
  //     let response = await fetch('http://99f1ba01.ngrok.io/DivingBackend/public/api/article/1');
  //     let responseJson = await response.json();
  //     this.setState({
  //       htmlTxt: responseJson.item[0].content
  //     })
  //     console.log(this.state.htmlTxt)

  //   }
  //   catch (err) {
  //     navigate('errorPage')
  //     console.log('err:', err)
  //   }
  // }

  componentDidMount = () => {
    this.setState({
      htmlTxt: htmlContent
    })
  }

  keyExtractor = (item, index) => { return index.toString() };

  render() {
    return (
      <WebView
        style={{ flex: 1, width: '100%' }}
        // source={{ uri: 'http://girldive.pixnet.net/blog/post/334541698-%E3%80%90%E5%8F%B0%E7%81%A3%E8%87%AA%E7%94%B1%E6%BD%9B%E6%B0%B4%E6%BD%9B%E9%BB%9E%E4%BB%8B%E7%B4%B9%E3%80%91' }}
        source={{ html: this.state.htmlTxt, baseUrl: '' }}
      />
    )
  }
}


